# Generated by Django 5.0.6 on 2024-07-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='raterecipe',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='saved',
        ),
        migrations.CreateModel(
            name='RecipeSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='recipe.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
