# Generated by Django 5.0.6 on 2024-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_owner_raterecipe_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raterecipe',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
