# Generated by Django 5.0.6 on 2024-07-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_raterecipe_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raterecipe',
            name='count',
        ),
    ]
